## **STATE** **CONTROL** **RENEWABLE** **ENERGY** **GENERATION**

**OBJECTIVE (Problem statement)**

1.Centralized data management

2.Performance monitiring

3.Decision support

4.Transparancy and reporting

5.Data analysing and forecasting

6.sustainability Assessment


**EXPECTED OUTCOMES**

1.Centralized renewable energy database,

2.improved data assessiblity

3,Enhanced monitoring and controal

4,Data- driven desicion making

5.incressed operational efficiency

6.Accurate forecasting

7.Regulatory complience

8.Environmrntal impact assesssment

9.Transperancy and accountablity

10.Support for sustainable development

 **DOMAIN**

 Renewable Energy  and enery Managment,
 smart grid and power distribution

**DATASET INFORMATION**

source:Ministry of power/https://indiadataportal.com/p/power/r/mop-renewable_energy_state-st-dl-abc

Year/Timeline:2019-2024

In [1]:
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/stephenkumar092-commits/State-Renewable-Energy-Generation/refs/heads/main/state-control-renewable-energy-generation.csv")

print(df.head())

   id        date         state_name  state_code                region  \
0   0  28-05-2020          All India          99                   NaN
1   1  28-05-2020     Andhra Pradesh          28       Southern Region
2   2  28-05-2020  Arunachal Pradesh          12  North-Eastern Region
3   3  28-05-2020              Assam          18  North-Eastern Region
4   4  28-05-2020              Bihar          10        Eastern Region

   wind_energy  solar_energy  other_renewable_energy  total_renewable_energy
0       323.73        131.64                   40.70                  496.07
1        29.95          9.23                    0.00                   39.18
2         0.00          0.00                    0.00                    0.00
3         0.00          0.00                    0.00                    0.00
4         0.00          0.00                    0.59                    0.59

In [2]:
#1 Data Loading and initial Overview

# number of rows and columns

# display first 5 rows
print("first 5 rows:")
print(df.head())

first 5 rows:
   id        date         state_name  state_code                region  \
0   0  28-05-2020          All India          99                   NaN
1   1  28-05-2020     Andhra Pradesh          28       Southern Region
2   2  28-05-2020  Arunachal Pradesh          12  North-Eastern Region
3   3  28-05-2020              Assam          18  North-Eastern Region
4   4  28-05-2020              Bihar          10        Eastern Region

   wind_energy  solar_energy  other_renewable_energy  total_renewable_energy
0       323.73        131.64                   40.70                  496.07
1        29.95          9.23                    0.00                   39.18
2         0.00          0.00                    0.00                    0.00
3         0.00          0.00                    0.00                    0.00
4         0.00          0.00                    0.59                    0.59

In [3]:
# Number of rows and columns

print("/t dataset shape:")

print("Rows:",df.shape[0])

print("columns:",df.shape[1])

/t dataset shape:
Rows: 61845
columns: 9

In [4]:
# Data types of each column

print("/t Data types:")
print(df.dtypes)

/t Data types:
id                          int64
date                       object
state_name                 object
state_code                  int64
region                     object
wind_energy               float64
solar_energy              float64
other_renewable_energy    float64
total_renewable_energy    float64
dtype: object

In [5]:
# Initial observations (e.g, head(),info(),describe())

# Dataset informartion

print("/Dataset info:")
print(df.info())

/Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61845 entries, 0 to 61844
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      61845 non-null  int64
 1   date                    61845 non-null  object
 2   state_name              61845 non-null  object
 3   state_code              61845 non-null  int64
 4   region                  60073 non-null  object
 5   wind_energy             61797 non-null  float64
 6   solar_energy            61815 non-null  float64
 7   other_renewable_energy  61800 non-null  float64
 8   total_renewable_energy  61845 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 4.2+ MB
None

In [6]:
# Statistical summary

print("/t statistical summary:")
print(df.describe())

/t statistical summary:
                 id    state_code   wind_energy  solar_energy  \
count  61845.000000  61845.000000  61797.000000  61815.000000
mean   30922.000000     20.569343      9.036228      9.319911
std    17853.258036     17.229161     33.215295     28.678012
min        0.000000      1.000000      0.000000      0.000000
25%    15461.000000      9.000000      0.000000      0.000000
50%    30922.000000     18.000000      0.000000      0.100000
75%    46383.000000     29.000000      0.610000      7.500000
max    61844.000000     99.000000    486.830000    296.960000

       other_renewable_energy  total_renewable_energy
count            61800.000000            61845.000000
mean                 1.740550               20.083293
std                  5.875876               62.621622
min                 -5.930000               -0.010000
25%                  0.000000                0.000000
50%                  0.000000                0.880000
75%                  0.610000               13.500000
max                114.820000              727.500000

In [7]:
#2 Data Pre-processing

# check missing values

print("/t missing values:")
print(df.isnull().sum())

/t missing values:
id                           0
date                         0
state_name                   0
state_code                   0
region                    1772
wind_energy                 48
solar_energy                30
other_renewable_energy      45
total_renewable_energy       0
dtype: int64

In [8]:
# REMOVING DUPLICATES

# Check duplicate records
print(df.duplicated().sum())

0

In [9]:
# correcting data types
print(df.dtypes)

# convert date to integer
df['date'] = pd.to_datetime(df['date'])

energy_columns= ['solar_energy','wind_energy','other_renewable_energy','total_renewable_energy']

for col in energy_columns: df[col]=pd.to_numeric(df[col],errors='coerce')

id                          int64
date                       object
state_name                 object
state_code                  int64
region                     object
wind_energy               float64
solar_energy              float64
other_renewable_energy    float64
total_renewable_energy    float64
dtype: object

/tmp/ipykernel_6075/686361565.py:5: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['date'])

In [10]:
#Creating deriverd columns

df['total_renewable_energy']= (
    df['solar_energy']+ df['wind_energy']+ df['other_renewable_energy'])

df['solar_percentage']=(df['solar_energy']/df['total_renewable_energy'])*100

df['wind_percentage']= (df['wind_energy']/df['total_renewable_energy'])*100

df['other_renewable_energy_percentage']= (df['other_renewable_energy']/df['total_renewable_energy'])*100

df['growth_rate']=(df.groupby('state_name')['total_renewable_energy'].pct_change()*100 )

df[[ 'state_name','total_renewable_energy','solar_percentage','wind_percentage','other_renewable_energy_percentage']].head()

/tmp/ipykernel_6075/1994617185.py:12: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df['growth_rate']=(df.groupby('state_name')['total_renewable_energy'].pct_change()*100 )

,state_name,total_renewable_energy,solar_percentage,wind_percentage,other_renewable_energy_percentage
0,All India,496.07,26.536577,65.258935,8.204487
1,Andhra Pradesh,39.18,23.557938,76.442062,0.000000
2,Arunachal Pradesh,0.00,NaN,NaN,NaN
3,Assam,0.00,NaN,NaN,NaN
4,Bihar,0.59,0.000000,0.000000,100.000000

In [11]:
# filtering and aggregatting data

#Filltering data

# spcific date
filtered_data=df[df['date']== '2020-05-28']
print(filtered_data)

    id       date                                    state_name  state_code  \
0    0 2020-05-28                                     All India          99
1    1 2020-05-28                                Andhra Pradesh          28
2    2 2020-05-28                             Arunachal Pradesh          12
3    3 2020-05-28                                         Assam          18
4    4 2020-05-28                                         Bihar          10
5    5 2020-05-28                                    Chandigarh           4
6    6 2020-05-28                                  Chhattisgarh          22
7    7 2020-05-28                                         Delhi           7
8    8 2020-05-28                                           Goa          30
9    9 2020-05-28                                       Gujarat          24
10  10 2020-05-28                                       Haryana           6
11  11 2020-05-28                              Himachal Pradesh           2
12  12 2020-05-28                             Jammu And Kashmir           1
13  13 2020-05-28                                     Jharkhand          20
14  14 2020-05-28                                     Karnataka          29
15  15 2020-05-28                                        Kerala          32
16  16 2020-05-28                                Madhya Pradesh          23
17  17 2020-05-28                                   Maharashtra          27
18  18 2020-05-28                                       Manipur          14
19  19 2020-05-28                                     Meghalaya          17
20  20 2020-05-28                                       Mizoram          15
21  21 2020-05-28                                      Nagaland          13
22  22 2020-05-28                                        Odisha          21
23  23 2020-05-28                                    Puducherry          34
24  24 2020-05-28                                        Punjab           3
25  25 2020-05-28                                     Rajasthan           8
26  26 2020-05-28                                        Sikkim          11
27  27 2020-05-28                                    Tamil Nadu          33
28  28 2020-05-28                                     Telangana          36
29  29 2020-05-28  The Dadra And Nagar Haveli And Daman And Diu          38
30  30 2020-05-28                                       Tripura          16
31  31 2020-05-28                                 Uttar Pradesh           9
32  32 2020-05-28                                   Uttarakhand           5
33  33 2020-05-28                                   West Bengal          19

                  region  wind_energy  solar_energy  other_renewable_energy  \
0                    NaN       323.73        131.64                   40.70
1        Southern Region        29.95          9.23                    0.00
2   North-Eastern Region         0.00          0.00                    0.00
3   North-Eastern Region         0.00          0.00                    0.00
4         Eastern Region         0.00          0.00                    0.59
5        Northern Region         0.00          0.00                    0.00
6         Western Region         0.00          0.20                    0.00
7        Northern Region         0.00          0.00                    0.62
8         Western Region         0.00          0.00                    0.00
9         Western Region        94.70         11.10                    0.30
10       Northern Region         0.00          0.14                    0.42
11       Northern Region         0.00          0.00                   10.43
12       Northern Region         0.00          0.00                    0.00
13        Eastern Region         0.00          0.00                    0.00
14       Southern Region        27.87         28.96                    5.87
15       Southern Region         0.54          0.39                    0.00
16        Western Region        37.80          8.80                    0.20
17        Western Region        41.90          8.30                    0.00
18  North-Eastern Region         0.00          0.00                    0.00
19  North-Eastern Region         0.00          0.00                    0.00
20  North-Eastern Region         0.00          0.00                    0.00
21  North-Eastern Region         0.00          0.00                    0.00
22        Eastern Region         0.00          0.00                    1.39
23       Southern Region         0.00          0.00                    0.00
24       Northern Region         0.00          3.41                    3.32
25       Northern Region        55.63         17.75                    4.82
26        Eastern Region         0.00          0.00                    0.00
27       Southern Region        34.65         14.93                    0.00
28       Southern Region         0.69         22.29                    0.00
29        Western Region         0.00          0.00                    0.00
30  North-Eastern Region         0.00          0.00                    0.00
31       Northern Region         0.00          5.40                    9.60
32       Northern Region         0.00          0.74                    0.26
33        Eastern Region         0.00          0.00                    2.88

    total_renewable_energy  solar_percentage  wind_percentage  \
0                   496.07         26.536577        65.258935
1                    39.18         23.557938        76.442062
2                     0.00               NaN              NaN
3                     0.00               NaN              NaN
4                     0.59          0.000000         0.000000
5                     0.00               NaN              NaN
6                     0.20        100.000000         0.000000
7                     0.62          0.000000         0.000000
8                     0.00               NaN              NaN
9                   106.10         10.461828        89.255419
10                    0.56         25.000000         0.000000
11                   10.43          0.000000         0.000000
12                    0.00               NaN              NaN
13                    0.00               NaN              NaN
14                   62.70         46.188198        44.449761
15                    0.93         41.935484        58.064516
16                   46.80         18.803419        80.769231
17                   50.20         16.533865        83.466135
18                    0.00               NaN              NaN
19                    0.00               NaN              NaN
20                    0.00               NaN              NaN
21                    0.00               NaN              NaN
22                    1.39          0.000000         0.000000
23                    0.00               NaN              NaN
24                    6.73         50.668648         0.000000
25                   78.20         22.698210        71.138107
26                    0.00               NaN              NaN
27                   49.58         30.112949        69.887051
28                   22.98         96.997389         3.002611
29                    0.00               NaN              NaN
30                    0.00               NaN              NaN
31                   15.00         36.000000         0.000000
32                    1.00         74.000000         0.000000
33                    2.88          0.000000         0.000000

    other_renewable_energy_percentage  growth_rate
0                            8.204487          NaN
1                            0.000000          NaN
2                                 NaN          NaN
3                                 NaN          NaN
4                          100.000000          NaN
5                                 NaN          NaN
6                            0.000000          NaN
7                          100.000000          NaN
8                                 NaN          NaN
9                            0.282752          NaN
10                          75.000000          NaN
11                         100.000000          NaN
12                                NaN          NaN
13                                NaN          NaN
14                           9.362041          NaN
15                           0.000000          NaN
16                           0.427350          NaN
17                           0.000000          NaN
18                                NaN          NaN
19                                NaN          NaN
20                                NaN          NaN
21                                NaN          NaN
22                         100.000000          NaN
23                                NaN          NaN
24                          49.331352          NaN
25                           6.163683          NaN
26                                NaN          NaN
27                           0.000000          NaN
28                           0.000000          NaN
29                                NaN          NaN
30                                NaN          NaN
31                          64.000000          NaN
32                          26.000000          NaN
33                         100.000000          NaN

In [12]:
#filter specific state

Tamil_Nadu_data= df[df['state_name']=='Tamil Nadu']
print(Tamil_Nadu_data.head())

      id       date  state_name  state_code           region  wind_energy  \
27    27 2020-05-28  Tamil Nadu          33  Southern Region        34.65
61    61 2020-05-29  Tamil Nadu          33  Southern Region        25.40
95    95 2020-05-30  Tamil Nadu          33  Southern Region        23.55
128  128 2020-06-01  Tamil Nadu          33  Southern Region        35.65
161  161 2020-06-02  Tamil Nadu          33  Southern Region        40.36

     solar_energy  other_renewable_energy  total_renewable_energy  \
27          14.93                     0.0                   49.58
61          11.49                     0.0                   36.89
95          17.09                     0.0                   40.64
128         17.17                     0.0                   52.82
161         18.43                     0.0                   58.79

     solar_percentage  wind_percentage  other_renewable_energy_percentage  \
27          30.112949        69.887051                                0.0
61          31.146652        68.853348                                0.0
95          42.052165        57.947835                                0.0
128         32.506626        67.493374                                0.0
161         31.348869        68.651131                                0.0

     growth_rate
27           NaN
61    -25.594998
95     10.165356
128    29.970472
161    11.302537

In [13]:
# Aggregatting data

#State wise total Renewable energy generation

state_generation= df.groupby('state_name')['total_renewable_energy'].sum()
print(state_generation)

state_name
All India                                       620452.28
Andhra Pradesh                                   56885.94
Arunachal Pradesh                                    3.89
Assam                                              944.29
Bihar                                             1203.14
Chandigarh                                           0.00
Chhattisgarh                                      3224.52
Delhi                                             1953.43
Goa                                                 33.57
Gujarat                                         102812.34
Haryana                                           3198.40
Himachal Pradesh                                 13206.23
Jammu And Kashmir                                   64.55
Jharkhand                                           15.16
Karnataka                                       108543.12
Kerala                                            2472.52
Ladakh                                               0.00
Madhya Pradesh                                   33952.80
Maharashtra                                      53574.70
Manipur                                              0.45
Meghalaya                                            0.10
Mizoram                                             86.26
Nagaland                                             0.00
Odisha                                            3367.56
Puducherry                                         139.37
Punjab                                           10287.20
Rajasthan                                        69357.70
Sikkim                                               5.45
Tamil Nadu                                      101074.77
Telangana                                        33132.72
The Dadra And Nagar Haveli And Daman And Diu        69.80
Tripura                                             29.49
Uttar Pradesh                                    17103.32
Uttarakhand                                       1516.18
West Bengal                                       3099.05
Name: total_renewable_energy, dtype: float64

In [14]:
#Average generation by state

Avg_gneration=df.groupby('state_name')['total_renewable_energy'].mean()
print(Avg_gneration)

state_name
All India                                       350.142370
Andhra Pradesh                                   32.066483
Arunachal Pradesh                                 0.002193
Assam                                             0.532294
Bihar                                             0.678207
Chandigarh                                        0.000000
Chhattisgarh                                      1.817655
Delhi                                             1.101144
Goa                                               0.018923
Gujarat                                          57.889831
Haryana                                           1.802931
Himachal Pradesh                                  7.444324
Jammu And Kashmir                                 0.036387
Jharkhand                                         0.008536
Karnataka                                        61.116622
Kerala                                            1.393754
Ladakh                                            0.000000
Madhya Pradesh                                   19.117568
Maharashtra                                      30.182930
Manipur                                           0.000254
Meghalaya                                         0.000056
Mizoram                                           0.048625
Nagaland                                          0.000000
Odisha                                            1.898286
Puducherry                                        0.078563
Punjab                                            5.798873
Rajasthan                                        39.052759
Sikkim                                            0.003072
Tamil Nadu                                       56.975631
Telangana                                        18.676843
The Dadra And Nagar Haveli And Daman And Diu      0.039302
Tripura                                           0.016623
Uttar Pradesh                                     9.641105
Uttarakhand                                       0.854667
West Bengal                                       1.746928
Name: total_renewable_energy, dtype: float64

In [15]:
# Maximum generation by state

Max_generation=df.groupby ('state_name')['total_renewable_energy'].max()
print(Max_generation)

state_name
All India                                       727.50
Andhra Pradesh                                   90.30
Arunachal Pradesh                                 2.80
Assam                                             3.32
Bihar                                             2.17
Chandigarh                                        0.00
Chhattisgarh                                    117.30
Delhi                                             2.28
Goa                                              33.57
Gujarat                                         156.80
Haryana                                          13.28
Himachal Pradesh                                 17.38
Jammu And Kashmir                                14.43
Jharkhand                                         2.60
Karnataka                                       126.58
Kerala                                           96.05
Ladakh                                            0.00
Madhya Pradesh                                  110.20
Maharashtra                                      80.20
Manipur                                           0.45
Meghalaya                                         0.10
Mizoram                                           1.58
Nagaland                                          0.00
Odisha                                           11.56
Puducherry                                       77.08
Punjab                                            9.68
Rajasthan                                       101.87
Sikkim                                            2.64
Tamil Nadu                                      148.13
Telangana                                        80.93
The Dadra And Nagar Haveli And Daman And Diu     69.80
Tripura                                           2.64
Uttar Pradesh                                    83.26
Uttarakhand                                       5.19
West Bengal                                      89.00
Name: total_renewable_energy, dtype: float64

In [16]:
# SOURCE_WISE TOTAL ENERGY

source_energy=df[['solar_energy','wind_energy','other_renewable_energy']].sum()
print(source_energy)

solar_energy              576110.28
wind_energy               558411.78
other_renewable_energy    107565.97
dtype: float64

In [17]:
state_summary= df.groupby('state_name').agg({'total_renewable_energy':['sum','mean','max'],
'solar_energy':'sum','wind_energy':'sum'})

print(state_summary)

                                             total_renewable_energy  \
                                                                sum
state_name
All India                                                 620452.28
Andhra Pradesh                                             56885.94
Arunachal Pradesh                                              3.89
Assam                                                        944.29
Bihar                                                       1203.14
Chandigarh                                                     0.00
Chhattisgarh                                                3224.52
Delhi                                                       1953.43
Goa                                                           33.57
Gujarat                                                   102812.34
Haryana                                                     3198.40
Himachal Pradesh                                           13206.23
Jammu And Kashmir                                             64.55
Jharkhand                                                     15.16
Karnataka                                                 108543.12
Kerala                                                      2472.52
Ladakh                                                         0.00
Madhya Pradesh                                             33952.80
Maharashtra                                                53574.70
Manipur                                                        0.45
Meghalaya                                                      0.10
Mizoram                                                       86.26
Nagaland                                                       0.00
Odisha                                                      3367.56
Puducherry                                                   139.37
Punjab                                                     10287.20
Rajasthan                                                  69357.70
Sikkim                                                         5.45
Tamil Nadu                                                101074.77
Telangana                                                  33132.72
The Dadra And Nagar Haveli And Daman And Diu                  69.80
Tripura                                                       29.49
Uttar Pradesh                                              17103.32
Uttarakhand                                                 1516.18
West Bengal                                                 3099.05

                                                                 solar_energy  \
                                                    mean     max          sum
state_name
All India                                     350.142370  727.50    287833.54
Andhra Pradesh                                 32.066483   90.30     21259.30
Arunachal Pradesh                               0.002193    2.80         0.94
Assam                                           0.532294    3.32       944.71
Bihar                                           0.678207    2.17       663.25
Chandigarh                                      0.000000    0.00         0.00
Chhattisgarh                                    1.817655  117.30      2458.67
Delhi                                           1.101144    2.28         1.61
Goa                                             0.018923   33.57         7.76
Gujarat                                        57.889831  156.80     41074.27
Haryana                                         1.802931   13.28      1081.79
Himachal Pradesh                                7.444324   17.38       106.62
Jammu And Kashmir                               0.036387   14.43        18.28
Jharkhand                                       0.008536    2.60         6.13
Karnataka                                      61.116622  126.58     45721.26
Kerala                                          1.393754   96.05      1727.60
Ladakh                                          0.000000    0.00         0.00
Madhya Pradesh                                 19.117568  110.20     13131.90
Maharashtra                                    30.182930   80.20     20310.00
Manipur                                         0.000254    0.45         0.45
Meghalaya                                       0.000056    0.10         0.10
Mizoram                                         0.048625    1.58        86.38
Nagaland                                        0.000000    0.00         0.00
Odisha                                          1.898286   11.56      1764.48
Puducherry                                      0.078563   77.08        99.35
Punjab                                          5.798873    9.68      5828.03
Rajasthan                                      39.052759  101.87     39674.17
Sikkim                                          0.003072    2.64         2.64
Tamil Nadu                                     56.975631  148.13     43136.32
Telangana                                      18.676843   80.93     31522.11
The Dadra And Nagar Haveli And Daman And Diu    0.039302   69.80         6.10
Tripura                                         0.016623    2.64        29.46
Uttar Pradesh                                   9.641105   83.26     16350.19
Uttarakhand                                     0.854667    5.19       968.28
West Bengal                                     1.746928   89.00       294.59

                                             wind_energy
                                                     sum
state_name
All India                                      278902.95
Andhra Pradesh                                  35686.45
Arunachal Pradesh                                   0.00
Assam                                               0.00
Bihar                                               0.00
Chandigarh                                          0.00
Chhattisgarh                                      185.30
Delhi                                               0.00
Goa                                                25.81
Gujarat                                         61527.47
Haryana                                             0.00
Himachal Pradesh                                    0.00
Jammu And Kashmir                                   0.00
Jharkhand                                           0.00
Karnataka                                       41077.47
Kerala                                            740.32
Ladakh                                              0.00
Madhya Pradesh                                  18921.30
Maharashtra                                     33275.80
Manipur                                             0.00
Meghalaya                                           0.00
Mizoram                                             0.00
Nagaland                                            0.00
Odisha                                              0.00
Puducherry                                         40.14
Punjab                                              1.83
Rajasthan                                       28469.48
Sikkim                                              0.00
Tamil Nadu                                      57993.82
Telangana                                        1428.65
The Dadra And Nagar Haveli And Daman And Diu       63.70
Tripura                                             0.00
Uttar Pradesh                                      71.29
Uttarakhand                                         0.00
West Bengal                                         0.00

In [18]:
#3 Exploratory Data Analysis

df.describe()

#(i) Univariate Analysis
energy_cols=['solar_energy','wind_energy','other_renewable_energy','total_renewable_energy']
print(df[energy_cols].describe())

       solar_energy   wind_energy  other_renewable_energy  \
count  61815.000000  61797.000000            61800.000000
mean       9.319911      9.036228                1.740550
std       28.678012     33.215295                5.875876
min        0.000000      0.000000               -5.930000
25%        0.000000      0.000000                0.000000
50%        0.100000      0.000000                0.000000
75%        7.500000      0.610000                0.610000
max      296.960000    486.830000              114.820000

       total_renewable_energy
count            61788.000000
mean                20.097920
std                 62.649017
min                 -0.010000
25%                  0.000000
50%                  0.880000
75%                 13.500000
max                727.500000

In [19]:
#State Distribution

print(df['state_name'].value_counts())

state_name
Jharkhand                                       1778
Arunachal Pradesh                               1776
Andhra Pradesh                                  1776
Meghalaya                                       1776
Assam                                           1776
Chandigarh                                      1776
Bihar                                           1776
Delhi                                           1776
Goa                                             1776
Gujarat                                         1776
Chhattisgarh                                    1776
Haryana                                         1776
Himachal Pradesh                                1776
Jammu And Kashmir                               1776
Karnataka                                       1776
Kerala                                          1776
Madhya Pradesh                                  1776
Maharashtra                                     1776
Manipur                                         1776
Tamil Nadu                                      1776
Mizoram                                         1776
Nagaland                                        1776
Odisha                                          1776
Puducherry                                      1776
Punjab                                          1776
Rajasthan                                       1776
Sikkim                                          1776
Uttar Pradesh                                   1776
Telangana                                       1776
The Dadra And Nagar Haveli And Daman And Diu    1776
Tripura                                         1776
West Bengal                                     1776
Uttarakhand                                     1776
All India                                       1772
Ladakh                                          1463
Name: count, dtype: int64

In [20]:
#date distribution

print(df['date'].value_counts().sort_index())

date
2020-05-28    34
2020-05-29    34
2020-05-30    34
2020-06-01    33
2020-06-02    33
              ..
2025-04-23    35
2025-04-24    35
2025-04-25    35
2025-04-26    35
2025-04-27    35
Name: count, Length: 1776, dtype: int64

In [21]:
#(ii) Bivariate Analysis

#State_wise

state_avg= df.groupby('state_name')['total_renewable_energy'].mean()

print(state_avg.sort_values(ascending=False))

state_name
All India                                       350.142370
Karnataka                                        61.116622
Gujarat                                          57.889831
Tamil Nadu                                       56.975631
Rajasthan                                        39.052759
Andhra Pradesh                                   32.066483
Maharashtra                                      30.182930
Madhya Pradesh                                   19.117568
Telangana                                        18.676843
Uttar Pradesh                                     9.641105
Himachal Pradesh                                  7.444324
Punjab                                            5.798873
Odisha                                            1.898286
Chhattisgarh                                      1.817655
Haryana                                           1.802931
West Bengal                                       1.746928
Kerala                                            1.393754
Delhi                                             1.101144
Uttarakhand                                       0.854667
Bihar                                             0.678207
Assam                                             0.532294
Puducherry                                        0.078563
Mizoram                                           0.048625
The Dadra And Nagar Haveli And Daman And Diu      0.039302
Jammu And Kashmir                                 0.036387
Goa                                               0.018923
Tripura                                           0.016623
Jharkhand                                         0.008536
Sikkim                                            0.003072
Arunachal Pradesh                                 0.002193
Manipur                                           0.000254
Meghalaya                                         0.000056
Chandigarh                                        0.000000
Ladakh                                            0.000000
Nagaland                                          0.000000
Name: total_renewable_energy, dtype: float64

In [22]:
#Date_wise

date_generation= df.groupby('date')['total_renewable_energy'].sum()

print(date_generation)

date
2020-05-28    992.14
2020-05-29    897.88
2020-05-30    663.14
2020-06-01    260.98
2020-06-02    299.90
               ...
2025-04-23    833.06
2025-04-24    884.90
2025-04-25    899.86
2025-04-26    809.02
2025-04-27    793.00
Name: total_renewable_energy, Length: 1776, dtype: float64

In [23]:
 #solar_energy vs total_renewable_energy

df[['solar_energy','total_renewable_energy']].corr()

                        solar_energy  total_renewable_energy
solar_energy                1.000000                0.928951
total_renewable_energy      0.928951                1.000000

In [24]:
#(iii) Multivarite analysis

# Groupby analysis

state_name_date = df.groupby(['state_name','date'])['total_renewable_energy'].sum()
print(state_name_date)

state_name   date
All India    2020-05-28    496.07
             2020-05-29    448.94
             2020-05-30    331.57
             2020-06-05    360.98
             2020-06-06    383.51
                            ...
West Bengal  2025-04-23      1.04
             2025-04-24      2.72
             2025-04-25      1.08
             2025-04-26      1.01
             2025-04-27      0.62
Name: total_renewable_energy, Length: 61843, dtype: float64

In [25]:
# miltiple aggregations

summary=df.groupby('state_name').agg({'solar_energy':'sum','wind_energy':'sum','other_renewable_energy':'sum','total_renewable_energy':['sum','mean']})

print(summary)

                                             solar_energy wind_energy  \
                                                      sum         sum
state_name
All India                                       287833.54   278902.95
Andhra Pradesh                                   21259.30    35686.45
Arunachal Pradesh                                    0.94        0.00
Assam                                              944.71        0.00
Bihar                                              663.25        0.00
Chandigarh                                           0.00        0.00
Chhattisgarh                                      2458.67      185.30
Delhi                                                1.61        0.00
Goa                                                  7.76       25.81
Gujarat                                          41074.27    61527.47
Haryana                                           1081.79        0.00
Himachal Pradesh                                   106.62        0.00
Jammu And Kashmir                                   18.28        0.00
Jharkhand                                            6.13        0.00
Karnataka                                        45721.26    41077.47
Kerala                                            1727.60      740.32
Ladakh                                               0.00        0.00
Madhya Pradesh                                   13131.90    18921.30
Maharashtra                                      20310.00    33275.80
Manipur                                              0.45        0.00
Meghalaya                                            0.10        0.00
Mizoram                                             86.38        0.00
Nagaland                                             0.00        0.00
Odisha                                            1764.48        0.00
Puducherry                                          99.35       40.14
Punjab                                            5828.03        1.83
Rajasthan                                        39674.17    28469.48
Sikkim                                               2.64        0.00
Tamil Nadu                                       43136.32    57993.82
Telangana                                        31522.11     1428.65
The Dadra And Nagar Haveli And Daman And Diu         6.10       63.70
Tripura                                             29.46        0.00
Uttar Pradesh                                    16350.19       71.29
Uttarakhand                                        968.28        0.00
West Bengal                                        294.59        0.00

                                             other_renewable_energy  \
                                                                sum
state_name
All India                                                  53715.79
Andhra Pradesh                                                 0.00
Arunachal Pradesh                                              2.95
Assam                                                          0.59
Bihar                                                        540.35
Chandigarh                                                     0.00
Chhattisgarh                                                 586.05
Delhi                                                       1954.32
Goa                                                            0.00
Gujarat                                                      210.60
Haryana                                                     2122.20
Himachal Pradesh                                           13108.10
Jammu And Kashmir                                             46.27
Jharkhand                                                      9.03
Karnataka                                                  21744.39
Kerala                                                         8.13
Ladakh                                                         0.00
Madhya Pradesh                                              1899.60
Maharashtra                                                   11.50
Manipur                                                        0.00
Meghalaya                                                      0.00
Mizoram                                                        0.00
Nagaland                                                       0.00
Odisha                                                      1604.94
Puducherry                                                     0.00
Punjab                                                      4468.00
Rajasthan                                                   1214.05
Sikkim                                                         2.81
Tamil Nadu                                                    40.30
Telangana                                                    221.07
The Dadra And Nagar Haveli And Daman And Diu                   0.00
Tripura                                                        0.05
Uttar Pradesh                                                700.24
Uttarakhand                                                  550.18
West Bengal                                                 2804.46

                                             total_renewable_energy  \
                                                                sum
state_name
All India                                                 620452.28
Andhra Pradesh                                             56885.94
Arunachal Pradesh                                              3.89
Assam                                                        944.29
Bihar                                                       1203.14
Chandigarh                                                     0.00
Chhattisgarh                                                3224.52
Delhi                                                       1953.43
Goa                                                           33.57
Gujarat                                                   102812.34
Haryana                                                     3198.40
Himachal Pradesh                                           13206.23
Jammu And Kashmir                                             64.55
Jharkhand                                                     15.16
Karnataka                                                 108543.12
Kerala                                                      2472.52
Ladakh                                                         0.00
Madhya Pradesh                                             33952.80
Maharashtra                                                53574.70
Manipur                                                        0.45
Meghalaya                                                      0.10
Mizoram                                                       86.26
Nagaland                                                       0.00
Odisha                                                      3367.56
Puducherry                                                   139.37
Punjab                                                     10287.20
Rajasthan                                                  69357.70
Sikkim                                                         5.45
Tamil Nadu                                                101074.77
Telangana                                                  33132.72
The Dadra And Nagar Haveli And Daman And Diu                  69.80
Tripura                                                       29.49
Uttar Pradesh                                              17103.32
Uttarakhand                                                 1516.18
West Bengal                                                 3099.05


                                                    mean
state_name
All India                                     350.142370
Andhra Pradesh                                 32.066483
Arunachal Pradesh                               0.002193
Assam                                           0.532294
Bihar                                           0.678207
Chandigarh                                      0.000000
Chhattisgarh                                    1.817655
Delhi                                           1.101144
Goa                                             0.018923
Gujarat                                        57.889831
Haryana                                         1.802931
Himachal Pradesh                                7.444324
Jammu And Kashmir                               0.036387
Jharkhand                                       0.008536
Karnataka                                      61.116622
Kerala                                          1.393754
Ladakh                                          0.000000
Madhya Pradesh                                 19.117568
Maharashtra                                    30.182930
Manipur                                         0.000254
Meghalaya                                       0.000056
Mizoram                                         0.048625
Nagaland                                        0.000000
Odisha                                          1.898286
Puducherry                                      0.078563
Punjab                                          5.798873
Rajasthan                                      39.052759
Sikkim                                          0.003072
Tamil Nadu                                     56.975631
Telangana                                      18.676843
The Dadra And Nagar Haveli And Daman And Diu    0.039302
Tripura                                         0.016623
Uttar Pradesh                                   9.641105
Uttarakhand                                     0.854667
West Bengal                                     1.746928

In [26]:
# pivot table

# state vs date
pivot_table= pd.pivot_table (df,
                            values='total_renewable_energy',
                            index= 'state_name',
                            columns= 'date',
                            aggfunc= 'sum')

print(pivot_table)

date                                          2020-05-28  2020-05-29  \
state_name
All India                                         496.07      448.94
Andhra Pradesh                                     39.18       42.06
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.00        0.00
Bihar                                               0.59        0.62
Chandigarh                                          0.00        0.00
Chhattisgarh                                        0.20        1.00
Delhi                                               0.62        0.00
Goa                                                 0.00        0.00
Gujarat                                           106.10       99.20
Haryana                                             0.56        0.12
Himachal Pradesh                                   10.43        9.77
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          62.70       62.01
Kerala                                              0.93        0.70
Ladakh                                               NaN         NaN
Madhya Pradesh                                     46.80       39.30
Maharashtra                                        50.20       44.80
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.00        0.00
Nagaland                                            0.00        0.00
Odisha                                              1.39        1.37
Puducherry                                          0.00        0.00
Punjab                                              6.73        5.85
Rajasthan                                          78.20       74.42
Sikkim                                              0.00        0.00
Tamil Nadu                                         49.58       36.89
Telangana                                          22.98       21.67
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                      15.00        5.57
Uttarakhand                                         1.00        0.71
West Bengal                                         2.88        2.88

date                                          2020-05-30  2020-06-01  \
state_name
All India                                         331.57         NaN
Andhra Pradesh                                     25.38       14.27
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.00        0.00
Bihar                                               0.86        0.56
Chandigarh                                          0.00        0.00
Chhattisgarh                                        0.10        0.00
Delhi                                               1.04        0.79
Goa                                                 0.00        0.00
Gujarat                                            76.30       27.50
Haryana                                             0.60        0.81
Himachal Pradesh                                   10.06       11.65
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          41.57       34.45
Kerala                                              0.67        0.69
Ladakh                                               NaN         NaN
Madhya Pradesh                                     33.30       15.40
Maharashtra                                        28.50       26.00
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.00        0.00
Nagaland                                            0.00        0.00
Odisha                                              1.37        1.37
Puducherry                                          0.00        0.00
Punjab                                              5.89        6.92
Rajasthan                                          39.30       41.38
Sikkim                                              0.00        0.00
Tamil Nadu                                         40.64       52.82
Telangana                                          17.63       17.77
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                       4.90        4.80
Uttarakhand                                         0.58        0.92
West Bengal                                         2.88        2.88

date                                          2020-06-02  2020-06-03  \
state_name
All India                                            NaN         NaN
Andhra Pradesh                                     24.54       32.52
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.00        0.00
Bihar                                               0.52        0.44
Chandigarh                                          0.00        0.00
Chhattisgarh                                        0.00        0.10
Delhi                                               0.89        0.00
Goa                                                 0.00        0.00
Gujarat                                            27.50       26.00
Haryana                                             0.71        0.77
Himachal Pradesh                                   12.12       11.64
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          50.20       50.20
Kerala                                              0.62        0.83
Ladakh                                               NaN         NaN
Madhya Pradesh                                     15.40       11.90
Maharashtra                                        26.00       42.10
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.00        0.00
Nagaland                                            0.00        0.00
Odisha                                              1.38        1.36
Puducherry                                          0.00        0.00
Punjab                                              6.30        6.87
Rajasthan                                          42.72       32.43
Sikkim                                              0.00        0.00
Tamil Nadu                                         58.79       55.29
Telangana                                          19.20       18.85
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                       9.17        5.10
Uttarakhand                                         0.96        0.92
West Bengal                                         2.88        2.88

date                                          2020-06-04  2020-06-05  \
state_name
All India                                            NaN      360.98
Andhra Pradesh                                     44.43       39.76
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.00        0.00
Bihar                                               0.32        0.37
Chandigarh                                          0.00        0.00
Chhattisgarh                                        0.20        0.00
Delhi                                               0.71        0.53
Goa                                                 0.00        0.00
Gujarat                                            34.50       43.90
Haryana                                             0.54        0.59
Himachal Pradesh                                   11.09       11.24
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          64.57       66.14
Kerala                                              0.78        0.78
Ladakh                                               NaN         NaN
Madhya Pradesh                                     16.20       17.00
Maharashtra                                        35.90       36.70
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.00        0.00
Nagaland                                            0.00        0.00
Odisha                                              1.37        1.39
Puducherry                                          0.00        0.00
Punjab                                              6.55        6.52
Rajasthan                                          24.47       45.12
Sikkim                                              0.00        0.00
Tamil Nadu                                         53.76       59.89
Telangana                                          18.53       22.34
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                       5.00        5.20
Uttarakhand                                         0.60        0.63
West Bengal                                         2.88        2.88

date                                          2020-06-06  2020-06-07  ...  \
state_name                                                            ...
All India                                         383.51      383.86  ...
Andhra Pradesh                                     48.70       50.14  ...
Arunachal Pradesh                                   0.00        0.00  ...
Assam                                               0.00        0.00  ...
Bihar                                               0.52        0.65  ...
Chandigarh                                          0.00        0.00  ...
Chhattisgarh                                        0.10        0.10  ...
Delhi                                               0.00        1.05  ...
Goa                                                 0.00        0.00  ...
Gujarat                                            48.20       31.60  ...
Haryana                                             0.66        0.42  ...
Himachal Pradesh                                   11.43       11.39  ...
Jammu And Kashmir                                   0.00        0.00  ...
Jharkhand                                           0.00        0.00  ...
Karnataka                                          67.67       67.58  ...
Kerala                                              0.94        1.01  ...
Ladakh                                               NaN         NaN  ...
Madhya Pradesh                                     20.20       18.30  ...
Maharashtra                                        39.20       37.70  ...
Manipur                                             0.00        0.00  ...
Meghalaya                                           0.00        0.00  ...
Mizoram                                             0.00        0.00  ...
Nagaland                                            0.00        0.00  ...
Odisha                                              1.37        1.37  ...
Puducherry                                          0.00        0.00  ...
Punjab                                              6.62        6.51  ...
Rajasthan                                          32.15       42.68  ...
Sikkim                                              0.00        0.00  ...
Tamil Nadu                                         69.37       78.24  ...
Telangana                                          22.58       21.65  ...
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00  ...
Tripura                                             0.00        0.00  ...
Uttar Pradesh                                      10.13        9.96  ...
Uttarakhand                                         0.79        0.63  ...
West Bengal                                         2.88        2.88  ...

date                                          2025-04-18  2025-04-19  \
state_name
All India                                         494.21      527.67
Andhra Pradesh                                     26.03       26.77
Arunachal Pradesh                                   0.00        0.00
Assam                                               1.06        1.04
Bihar                                               0.57        1.07
Chandigarh                                          0.00        0.00
Chhattisgarh                                        5.10        4.70
Delhi                                               1.65        1.65
Goa                                                 0.00        0.00
Gujarat                                           119.50      140.40
Haryana                                             2.09        2.45
Himachal Pradesh                                   10.21        9.91
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          60.40       58.87
Kerala                                              1.77        1.95
Ladakh                                              0.00        0.00
Madhya Pradesh                                     36.70       43.20
Maharashtra                                        45.30       48.90
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.11        0.10
Nagaland                                            0.00        0.00
Odisha                                              2.94        2.84
Puducherry                                          0.05        0.06
Punjab                                              4.70        6.17
Rajasthan                                          80.36       74.15
Sikkim                                              0.00        0.00
Tamil Nadu                                         59.15       66.36
Telangana                                          18.49       19.70
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                      16.80       16.20
Uttarakhand                                         0.70        0.64
West Bengal                                         0.53        0.54

date                                          2025-04-20  2025-04-21  \
state_name
All India                                         476.94      403.74
Andhra Pradesh                                     27.24       24.80
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.82        0.84
Bihar                                               1.07        1.12
Chandigarh                                          0.00        0.00
Chhattisgarh                                        5.30        5.30
Delhi                                               1.62        1.75
Goa                                                 0.00        0.00
Gujarat                                           110.40       82.40
Haryana                                             2.37        2.21
Himachal Pradesh                                    9.77        9.70
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          56.10       53.20
Kerala                                              1.75        1.65
Ladakh                                              0.00        0.00
Madhya Pradesh                                     36.50       30.20
Maharashtra                                        46.10       37.40
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.13        0.14
Nagaland                                            0.00        0.00
Odisha                                              2.76        2.93
Puducherry                                          0.07        0.07
Punjab                                              6.02        5.80
Rajasthan                                          65.04       54.73
Sikkim                                              0.00        0.00
Tamil Nadu                                         65.57       49.67
Telangana                                          20.17       20.96
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00
Tripura                                             0.00        0.00
Uttar Pradesh                                      16.90       17.20
Uttarakhand                                         0.69        0.61
West Bengal                                         0.55        1.06

date                                          2025-04-22  2025-04-23  \
state_name
All India                                         397.04      416.53
Andhra Pradesh                                     21.81       21.74
Arunachal Pradesh                                   0.00        0.00
Assam                                               0.28        0.71
Bihar                                               1.12        1.22
Chandigarh                                          0.00        0.00
Chhattisgarh                                        5.70        5.50
Delhi                                               1.67        1.82
Goa                                                 0.00        0.00
Gujarat                                            91.90       98.00
Haryana                                             2.31        2.52
Himachal Pradesh                                    9.75        9.62
Jammu And Kashmir                                   0.00        0.00
Jharkhand                                           0.00        0.00
Karnataka                                          47.82       52.50
Kerala                                              1.46        1.75
Ladakh                                              0.00        0.00
Madhya Pradesh                                     25.20       22.90
Maharashtra                                        41.80       40.80
Manipur                                             0.00        0.00
Meghalaya                                           0.00        0.00
Mizoram                                             0.13        0.13
Nagaland                                            0.00        0.00
Odisha                                              3.11        3.00
Puducherry                                          0.07        0.07
Punjab                                              6.35        6.44
Rajasthan                                          54.03       49.99
Sikkim                                              0.00        0.00
Tamil Nadu                                         41.71       56.63
Telangana                                          21.12       21.22
The Dadra And Nagar Haveli And Daman And Diu        0.00        0.00

In [27]:
# correlation analysis

corr_matrix= df[['solar_energy','wind_energy','other_renewable_energy','total_renewable_energy']].corr()

print(corr_matrix)

                        solar_energy  wind_energy  other_renewable_energy  \
solar_energy                1.000000     0.749516                0.785656
wind_energy                 0.749516     1.000000                0.694328
other_renewable_energy      0.785656     0.694328                1.000000
total_renewable_energy      0.928951     0.938511                0.821656

                        total_renewable_energy
solar_energy                          0.928951
wind_energy                           0.938511
other_renewable_energy                0.821656
total_renewable_energy                1.000000